server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    # Schakel symlinks in voor storage
    disable_symlinks off;

    location / {
        # Dwing de browser om NOOIT de HTML te cachen
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
        
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Serveer storage bestanden correct
    location /storage/ {
        alias /var/www/storage/app/public/;
        add_header Access-Control-Allow-Origin *;
        autoindex on;
    }

    # Cache statische assets (JS/CSS) agressief, maar ALLEEN in de build_v* mappen
    location ~* /build_v.*/assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
