server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    # Belangrijk: Schakel symlinks in voor storage
    disable_symlinks off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Serveer storage bestanden correct
    location /storage/ {
        alias /var/www/storage/app/public/;
        add_header Access-Control-Allow-Origin *;
        autoindex on;
    }

    # Cache statische assets (JS/CSS) agressief, want Vite gebruikt hashes
    location /build/assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
